"""
Django settings for alicuotas project.

Generated by 'django-admin startproject' using Django 3.1a1.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+k_81w*#0#(w+i8znv=_m_b-e&6&(sh0#bg5)w6_dnp(v!#den'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['situaciones-emergencia.herokuapp.com','127.0.0.1']
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
#	'django_facebook',
    'bootstrap4',
    'bootstrap_datepicker_plus',
	'polls.apps.PollsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
BOOTSTRAP4 = {
    'include_jquery': True,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'alicuotas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'alicuotas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

#DATABASES = {
#    'default': {
#        #'ENGINE': 'django.db.backends.sqlite3',
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        #'NAME': BASE_DIR / 'db.sqlite3',
#        'NAME': 'situaciones_emergencia',
#        'USER': 'postgres',
#        'PASSWORD': 'postgresql',
#        'HOST': '127.0.0.1',
#        'PORT': '5432',
#    }
#}
#DATABASES = {
#    'default': {
#        #'ENGINE': 'django.db.backends.sqlite3',
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        #'NAME': BASE_DIR / 'db.sqlite3',
#        'NAME': 'd1nede6qv17th5',
#        'USER': 'ybfgdnpzkalqyh',
#        'PASSWORD': '9fbc0297c621aaf96e76a65084be5bc40c8a2c09590da6b9e81d3c4e7d697aec',
#        'HOST': 'ec2-54-81-37-115.compute-1.amazonaws.com',
#        'PORT': '5432',
#    }
#}
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "alicuotas",
        "USER": "root",
        "PASSWORD": "",
        "HOST": "localhost",
        'PORT': '3306',
        
    },
}

# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'es-ec'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
FACEBOOK_APP_ID=str('149396128507089')
FACEBOOK_APP_SECRET   = str('361000aa27740ded316caa5e169b8151')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
DEFAULT_AUTO_FIELD='django.db.models.AutoField'
