# Generated by Django 3.1a1 on 2020-05-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(verbose_name='date created')),
                ('from_id', models.CharField(max_length=100)),
                ('from_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('message_id', models.CharField(max_length=100)),
            ],
        ),
    ]
