# Generated by Django 3.1a1 on 2020-06-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200522_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='intensity',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='polarity',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='subjectivity',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=25, null=True),
        ),
    ]
