# Generated by Django 4.2.2 on 2023-06-27 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200531_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(verbose_name='date created')),
                ('code', models.CharField(max_length=100)),
                ('auction_date', models.DateTimeField()),
                ('property_type', models.TextField(verbose_name=100)),
                ('signaling', models.CharField(max_length=100)),
                ('expert_appraisal', models.DecimalField(blank=True, decimal_places=18, max_digits=25, null=True)),
                ('calculated_appraisal', models.DecimalField(blank=True, decimal_places=18, max_digits=25, null=True)),
                ('info', models.TextField()),
                ('limit', models.TextField()),
                ('property_area', models.TextField(max_length=100)),
                ('construction_area', models.TextField(max_length=100)),
                ('cadastral_key', models.TextField(max_length=100)),
                ('characteristics', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
                ('imagen', models.FileField(upload_to='media/')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ad')),
            ],
        ),
    ]
