# Generated by Django 4.2.2 on 2023-06-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_ad_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='location',
            field=models.TextField(null=True, verbose_name=100),
        ),
    ]
