# Generated by Django 4.2.2 on 2023-06-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_ad_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='auction_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='cadastral_key',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ad',
            name='characteristics',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='construction_area',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ad',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='limit',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='property_area',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ad',
            name='property_type',
            field=models.TextField(blank=True, verbose_name=100),
        ),
        migrations.AlterField(
            model_name='ad',
            name='signaling',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
