# Generated by Django 4.2.2 on 2023-06-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_ad_auction_date_alter_ad_cadastral_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='auction_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
