# Generated by Django 4.2.2 on 2023-07-06 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_ad_calculated_appraisal_decimal_ad_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='calculated_appraisal_decimal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 2, 28, 58, 816158, tzinfo=datetime.timezone.utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='expert_appraisal_decimal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
