# Generated by Django 4.2.2 on 2023-08-22 01:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_ad_favorite_alter_ad_created_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='ad',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 1, 44, 24, 223936, tzinfo=datetime.timezone.utc), verbose_name='date created'),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('number_property', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Aliquot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('reference', models.CharField(max_length=128)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.property')),
            ],
        ),
    ]
