# Generated by Django 4.2.2 on 2023-08-22 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_owner_alter_ad_created_time_property_aliquot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliquot',
            name='valor',
        ),
        migrations.AddField(
            model_name='aliquot',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 2, 2, 14, 798234, tzinfo=datetime.timezone.utc), verbose_name='date created'),
        ),
    ]
