# Generated by Django 4.2.2 on 2023-08-22 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_remove_aliquot_valor_aliquot_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='media',
            name='ad',
        ),
        migrations.AlterModelOptions(
            name='aliquot',
            options={'verbose_name': 'Alicuota', 'verbose_name_plural': 'Alicuotas'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Propietario', 'verbose_name_plural': 'Propietarios'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Inmueble', 'verbose_name_plural': 'Inmuebles'},
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
